---
- name: Converge
  hosts: all
  vars:
    docker_webapps:
    - name: samtris
      docker_image: blauwelucht/samtris:v2.0
      port: 8080
    - name: oogdesmeesters
      docker_image: ongoonku/oogdesmeestersjs:1.0
      port: 8080
    docker_webapps_use_lets_encrypt: false
    docker_webapps_domain_name: blauwe-lucht.nl
    docker_webapps_email_address: info@blauwelucht.nl
    docker_webapps_organization_name: Blauwe Lucht

  tasks:
  - name: Run role under test.
    include_role:
      name: ansible-role-docker-webapps
