---
# Inspired by https://github.com/jonashackt/molecule-ansible-docker-aws
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: docker-ubuntu-bionic
    image: ubuntu:bionic
    privileged: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare-docker-in-docker.yml
lint: |
  set -e
  yamllint .
  ansible-lint .
verifier:
  name: ansible
